// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akbqkcioeqrxozaqcixw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrYnFrY2lvZXFyeG96YXFjaXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzMwMTgsImV4cCI6MjA2MzU0OTAxOH0.H0-W4gdgSqV6qC5fjCSrcDdur3EkgQCr-bJv0pRp3M4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);